POST http://localhost:8081/api/file/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="fileName"; filename="test_upload.txt"

< "test_upload.txt"
--WebAppBoundary--





